### ISSUE TITLE
Uncaught TypeError: Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by yosefeliezrie** [fourcels/atom-package-sync#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [package-sync-plus](https://github.com/fourcels/atom-package-sync) package, v0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'content' of undefined

```
At /Users/yosefeliezrie/.atom/packages/package-sync-plus/lib/package-manager.coffee:88

TypeError: Cannot read property 'content' of undefined
    at /Users/yosefeliezrie/.atom/packages/package-sync-plus/lib/package-manager.coffee:88:56
    at /Users/yosefeliezrie/.atom/packages/package-sync-plus/lib/package-manager.coffee:69:7
    at /Users/yosefeliezrie/.atom/packages/package-sync-plus/node_modules/github/api/v3.0.0/gists.js:342:17
    at callCallback (/Users/yosefeliezrie/.atom/packages/package-sync-plus/node_modules/github/index.js:743:17)
    at IncomingMessage.<anonymous> (/Users/yosefeliezrie/.atom/packages/package-sync-plus/node_modules/github/index.js:796:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

### Commands

```
     -0:19.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:16.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.6.0 package-sync-plus:restore (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "package-sync"
    ]
  },
  "package-sync-plus": {
    "gistId": "0a05c755493c0badbec9074a974fd796",
    "personalAccessToken": "32324c58cb2d05110894d59565f8c475521814ec"
  }
}
```

### Installed Packages

```coffee
# User
package-sync-plus, v0.1.2
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by fourcels** [comment]
@yosefeliezrie 
you haven't generate `gist` for `package-sync-plus`

1. clear `package-sync-plus`'s `Gist Id`
2. trigger command `Packages` -> `Packages Sync Plus` -> `Backup`
